#! /bin/sh

cd /lib/modules/*/extra/

case "$1" in
start)
echo "Starting init script for Module Loading"
start-stop-daemon -S -n init -a /usr/bin/scull_load -- scull
start-stop-daemon -S -n init -a /usr/bin/module_load -- faulty 
insmod ./hello.ko
;;
stop)
echo "Removing user modules"
start-stop-daemon -K -n scull_load
start-stop-daemon -K -n module_load
start-stop-daemon -S -n init -a /usr/bin/scull_unload -- scull
start-stop-daemon -S -n init -a /usr/bin/module_unload -- faulty
rmmod hello
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
